### ISSUE TITLE
what bugs in Photo app? also in what macos version?

### ISSUE THREAD

**Issue by mailinglists35** [abentele/PhotosExporter#7] opened 2020-08-19 14:17 UTC
>History

>This program was not my first try. I've tried out some other solutions before, that didn't work at all:

>    export photos within the Photos app; this didn't work because of several annoying bugs of Photos (I've already reported the bugs to Apple).

i am just curious, what bugs have you discovered when exporting? i am keeping the photos library on a iscsi volume backed by zfs snapshots so i could instantly rollback an older working copy (assuming the zfs snapshot happened during a time when the db was consistent on disk...:D)

**Comment by abentele** [comment] 2020-08-21 21:40
There were several bugs (maybe you don't have permission to see the tickets on Apple's site):
- Photos: export folder doesn't export all albums of the folder (I don't want to leave it to chance which photos are exported and which are not...)
https://feedbackassistant.apple.com/feedback/5726923
- Photos export: progress indicator shows wrong value
https://feedbackassistant.apple.com/feedback/5739054
- Photos: Menu entry "Export folder" sometimes missing (and therefore it's not possible to export)
https://feedbackassistant.apple.com/feedback/5739050
- Photos: Export with "sequential" filename not really sequential
https://feedbackassistant.apple.com/feedback/5734630
- Photos: date of exported files: the exported files' file date is the current date instead of the date when the picture was taken
https://feedbackassistant.apple.com/feedback/5445509

All tickets are from years 2017 and 2018 and still open. Not any comment from Apple at all! This doesn't mean the bugs aren't fixed in current macOS, but I would expect some comments on these tickets if they are fixed or not.

Using zfs snapshots for your Photos Library may be an option, like any other backup solution (e.g. APFS snapshots, CCC, Time Machine). 

But having a backup of the very proprietary Photos Library was to not enough for me...
In my opinion, Photos Library is a very closed system: the PhotoKit API doesn't expose every information which is contained in the Photos Library; the problem is: even if I'm able to write code in Objective-C or Swift, it's not possible to get every information from the Photos Library and therefore it's not possible e.g. to migrate those information to any other photos application.

So a main goal of PhotosExporter was to get a backup with open directory structure which is application independent and therefore can be accessed and used with any application which can open Photos - e.g. Finder. Another example would be an application which can host photos in your private cloud.

Btw.: I think your question is answered with this ticket, therefore I close it.

**Closed as completed by abentele** 2020-08-21 21:40 UTC
