### ISSUE TITLE
The exported library have to be designed as System Photo Library

### ISSUE THREAD

**Issue by teoteo** [abentele/PhotosExporter#11] opened 2021-04-16 14:39 UTC
I’ve tried to create a new little library for some tests giving its **photosLibraryPath** in ~/Library/Application Support/PhotosExporter/PhotosExporter.yaml configuration file  but PhotosExporter exported the system library.
I had to designate it as [System Photo Library](https://support.apple.com/HT204414) to the export it.

- If is it by design, I suggest to write in [Readme.md](https://github.com/abentele/PhotosExporter/blob/master/Readme.md#usage) where photosLibraryPath is described.
- If it is a bug, just consider it as a bug, so if somebody can fix it is welcome :-)

**Comment by abentele** [comment] 2021-04-16 17:37
It's as designed, not a bug.
But you're right, this design is not good enough, and it's not well enough documented.

In my opinion it should be fixed by using the photosLibraryPath specified in the PhotosExporter.yaml configuration.

Remark: before, I've always exported the system photos library. The parameter photosLibraryPath is only needed because of direct access to the sqlite database which was introduced after switch from the MLMediaLibrary API to PhotoKit API. This parameter is a workaround for missing API, therefore it should not exist at all.

**Comment by RhetTbull** [comment] 2021-04-16 18:40
You can get the system Photos library path by reading key `SystemLibraryPath` from 
`~/Library/Containers/com.apple.photolibraryd/Data/Library/Preferences/com.apple.photolibraryd.plist`

You can open a non-default library using the undocumented `PHPhotoLibrary initWithPhotoLibraryURL`

There's some example code here:

https://github.com/neilpa/photohack/blob/1283e3936f6a57db267a437ab744808a2c67d203/photohack/PhotoProxy.m#L27-L41

**Comment by abentele** [comment] 2021-04-17 12:29
As it is not possible to read from Photos libraries other than System Library with public API, I removed the possibility to configure the Photos library, and documented it in the README.md.
The library path is read from the file, as @RhetTbull described.

Remark: I decided not to use another internal API as I personally don't need this feature. Feel free to implement it by yoursself in a fork if you need it. This is open source.

Therefore I close this issue.

**Closed as completed by abentele** 2021-04-17 12:29 UTC
